version: "3"

services:
  db:
    image: "postgres:12-alpine"
    container_name: "postgres-covid19"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    container_name: "web-covid19"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
