# Generated by Django 3.0.5 on 2020-04-19 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='LiveStatistic',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('new_cases', models.IntegerField(blank=True, null=True)),
                ('new_deaths', models.IntegerField(blank=True, null=True)),
                ('active_cases', models.IntegerField(blank=True, null=True)),
                ('critical', models.IntegerField(blank=True, null=True)),
                ('total_cases', models.IntegerField(blank=True, null=True)),
                ('total_deaths', models.IntegerField(blank=True, null=True)),
                ('total_recovered', models.IntegerField(blank=True,
                                                        null=True)),
                ('total_tests', models.IntegerField(blank=True, null=True)),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='live_statistics',
                                   to='stats.Country')),
            ],
            options={
                'verbose_name': 'Live statistic',
                'verbose_name_plural': 'Live statistics',
            },
        ),
    ]
